steps:
  - name: 'golang:stretch'
    entrypoint: 'go'
    dir: 'pod-exists'
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'pod-exists'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/checks/pod-exists:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/checks/pod-exists:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/checks/pod-exists:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/checks/pod-exists:latest'